version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./DockerFile
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:dev@db/dev
      FLASK_ENV: development
      FLASK_APP: "entrypoint:apk"
    networks:
      - default
    ports:
      - 7070:7070
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: dev
    image: postgres:10-alpine
    networks:
      - default
    ports:
      - 5431:5432
    restart: always
    volumes:
      - /var/lib/postgresql/data